### YamlMime:Certification
title: 'MCSA: Web Applications'
metadata:
  title: 'MCSA: Web Applications'
  description: 'MCSA: Web Applications'
uid: certification.mcsa-web-applications-certification
iconUrl: /media/learn/certification/badges/mcsa-badge.svg
summary: |-
  <div>
  <div><font color='red'><strong>코로나바이러스(COVID-19) 상황에 대응하여 Microsoft는 교육 및 인증 프로그램에 대한 몇 가지 임시 변경 조치를 시행하고 있습니다. <a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>자세히 알아보기</a>.</strong></font><br/><br/></div>
  <div><strong>본 인증은 2021년 1월 31일 중단됩니다. 해당일 이후부터는 본 인증을 더 이상 취득할 수 없습니다. 중단 일자 전에 취득한 모든 자격증은 <a href='https://www.microsoft.com/learning/dashboard.aspx'>인증 대시보드</a>에 있는 성적표에 계속 표시됩니다. 만료된 모든 인증서도 <a href='/learn/certifications/retired-certifications'>에서 찾아볼 수 있습니다</a>.</strong><br/><br/></div>
  </div>

  최신 웹 앱을 구현할 수 있는 귀하의 전문성을 입증하십시오.

  MCSA&#58; Web Applications 인증을 얻으려면, 다음 요구 사항을 충족해야 합니다&#58;
  - 다음 시험에 합격 [70-486&#58; Developing ASP.NET MVC Web Applications](/learn/certifications/exams/70-486)
  - 다음 시험 중 하나에 합격&#58;
    - [70-480&#58; Programming in HTML5 with JavaScript and CSS3](/learn/certifications/exams/70-480)
    - [70-483&#58; Programming in C#](/learn/certifications/exams/70-483)
subTitle: 최신 웹 앱을 구현할 수 있는 귀하의 전문성을 입증하십시오.
levels:
- intermediate
skills:
- none
roles:
- developer
type: mcsa
products:
- vs
courses:
- uid: course.20480
- uid: course.20483
- uid: course.20486
exams:
- uid: exam.70-480
- uid: exam.70-483
- uid: exam.70-486
resources:
- title: 교육 및 인증 가이드
  description: 간결한 교육 및 인증 가이드에서 모든 인증을 탐색하십시오.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: 인증 포스터
  description: 기초, 역할 기반 및 전문 인증에 대한 개요를 확인합니다.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: 성공 확률을 높여주는 두 가지 훌륭한 제안을 확인하세요.
  href: deals.md
- title: 인증 지원
  description: Microsoft Certification 지원 포럼에서 도움을 받으십시오. 포럼 조정자는 월요일에서 금요일까지 업무일 하루 만에 응답할 것입니다.
  href: help.md
- title: 인증 대시보드
  description: 예약된 약속, 인증서 및 스크립트를 검토하고 관리합니다.
  href: https://www.microsoft.com/learning/dashboard.aspx

